# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project 07 - PokedexGo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project 07 - PokedexGo
  pod 'Kingfisher', '~> 6.0'
end
